id: P006891
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:03.287779
source_metadata:
  id: bdr:W29518
  title: གངས་ལྗོངས་མདོ་སྨད་གནས་མཆོག་གསུམ་གྱི་གནས་ཡིག་ཕྱོགས་བསྒྲིགས་རྫོགས་ལྡན་འཕྲུལ་གྱི་མེ་ལོང
  author: ''
  volumes:
    bc778216b0cb413e8f2135a1aaca3c9b:
      image_group_id: I00EGS1017207
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
